//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_DepartementEmployee
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public string fonction { get; set; }
        public int salaire { get; set; }
        public int iddep { get; set; }
    
        public virtual departement departement { get; set; }
    }
}
